#!/usr/bin/env php
<?php

require __DIR__ . '/bootstrap.php';

$helperSet = new \Symfony\Component\Console\Helper\HelperSet();
$helperSet->set(new \PHPCR\Util\Console\Helper\PhpcrHelper($session));

$cli = new \Symfony\Component\Console\Application('PHPCR Command Line Interface', '0.1');
$cli->setCatchExceptions(true);
$cli->setHelperSet($helperSet);
$cli->addCommands(array(
    new \PHPCR\Util\Console\Command\NodeTypeRegisterCommand(),
));
$cli->run();
